version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    networks:
      - semapps
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: "admin"

  fuseki_compact:
    image: semapps/jena-fuseki-webacl:latest
    entrypoint: /docker-compact-entrypoint.sh
    profiles: 
      - compact
    volumes:
      - ./data/fuseki:/fuseki

  middleware:
    image: dataplayers/archipelago-middleware:0.8
    volumes:
      - './middleware/logs:/archipelago/middleware/logs'
      - './middleware/jwt:/archipelago/middleware/jwt'
      - './middleware/uploads:/archipelago/middleware/uploads'
      - './addOn:/archipelago/middleware/addOn'
      - './data/fuseki/databases/localData:/localData'
    environment:
      - 'SEMAPPS_SPARQL_ENDPOINT=http://fuseki:3030/'
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - 'SEMAPPS_HOME_URL=http://localhost:3000/'
      - 'SEMAPPS_OIDC_ISSUER=https://login.lescommuns.org/auth/realms/master/'
      - SEMAPPS_OIDC_CLIENT_ID=semapps
      - 'SEMAPPS_REDIS_URL=redis://redis:6379/0'
    command: bash -c "cp -r ./addOn/middleware/* . && pm2-runtime 'yarn run dev'"
    networks:
      - semapps
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./../PETR_MSB_tiers-lieux/frontend
      dockerfile: Dockerfile
    container_name: frontend_petr_enr
    networks:
      - semapps
    volumes:
      - ./../PETR_MSB_tiers-lieux/frontend:/app
    environment:
      #- REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_MIDDLEWARE_URL=https://data.petr-msb.data-players.com/
      - REACT_APP_MAPBOX_ACCESS_TOKEN=pk.eyJ1Ijoic3Jvc3NldDgxIiwiYSI6ImNrbDd0b2VkMzA1dDMycG9iemU4NnpuemsifQ.HvpZ3tnweVHEUYLb0tDvTg
      - PORT=4000
    restart: always
    depends_on:
      - middleware
    ports:
      - "4000:4000"
    command: bash -c "npm rebuild --silent && npm install --silent && npm install && npm start"
      
networks:
  semapps:
    name: semapps_network
